fix installtion step
Need to add the `shared_preload_libraries` before create extension.
```
root@citus3:~# sudo -i -u postgres psql -c "CREATE EXTENSION citus;"
ERROR:  Citus can only be loaded via shared_preload_libraries
HINT:  Add citus to shared_preload_libraries configuration variable in postgresql.conf in master and workers. Note that citus should be at the beginning of shared_preload_libraries.
```